### ISSUE TITLE
Running notebook in a path with a space causes an error related to globalScope not found

### ISSUE THREAD

**Issue by seglo** [spark-notebook/spark-notebook#681]
Hey,

We're using the spark-notebook for trainings and I was receiving errors when executing any cell.  I had the workbook unpacked with an absolute path that contained a space.

`<console>:11: error: not found: value globalScope`

As soon as I removed the space, everything started to work.  I didn't investigate further.

Platform: OSX 10.11.6
Spark notebook: spark-notebook-0.7.0-SNAPSHOT-scala-2.11.7-spark-1.6.0-hadoop-2.6.0-with-hive-with-parquet

**Comment by aronayne** [comment]
@seglo I'm receiving this issue also, I have no space in the path from where I launch Spark.

**Comment by Unlocker** [comment]
I have the same issue with OS Windows 7. Path to spark-notebook contains no spaces (c:\usr\spark-notebook). Can anyone help?

Build: |  buildTime-Thu Dec 15 07:20:33 UTC 2016 | formattedShaVersion-0.7.0-c955e71d0204599035f603109527e679aa3bd570 | sbtVersion-0.13.8 | scalaVersion-2.11.8 | sparkNotebookVersion-0.7.0 | hadoopVersion-2.7.3 | jets3tVersion-0.7.1 | jlineDef-(jline,2.12) | sparkVersion-2.0.2 | withHive-true |

**Comment by andypetrella** [comment]
@seglo @Unlocker @aronayne this should have been fixed on master (it's the path encoding problem)
LMK :-)

**Comment by yqren2005** [comment]
I am still seeing this issue on Windows 7 with spark-notebook-0.7.0-scala-2.11.8-spark-2.0.2-hadoop-2.7.3-with-hive:

<console>:12: error: not found: value globalScope

Also the default port is 9000 not 9001

**Comment by Unlocker** [comment]
@andypetrella thank you for the advice, it helps me. It will be useful to make new stable build fixing Windows specified issue .
@aronayne @yqren2005 checkout the master and build 0.8.0-SNAPSHOT. It works for me.

**Comment by yqren2005** [comment]
Yes 0.8 doesn't have this issue. Thanks for pointing out.
However, it seems auto-complete doesn't work no matter with Tab or
Ctrl+Space. It only works when I'm doing import.
Anyone has similar issue?

**Comment by neilpat1995** [comment]
@Unlocker I'm also facing this issue even after checking that my download path doesn't have any spaces. As a background on my setup approach, I downloaded a ZIP file with Spark and various other tools that I need from [here](http://spark-notebook.io/dl/zip/0.7.0/2.11/2.1.0/2.7.2/false/true), and then ran `.\bin\spark-notebook`, navigated to localhost:9000, and opened core/Spark-101 (following [this tutorial](https://github.com/andypetrella/spark-notebook/blob/master/docs/exploring_notebook.md)). Running the first import cell gave the same error: <br> `<console>:12: error: not found: value globalScope
       globalScope.sparkContext.setJobGroup("cell-B9C94C7E25F044A58CDDFC7704C2BDF9", "run-1485282537519: import org.apache.spark._import org.apache.spark.SparkContext._import org.apache.spark.rdd._")
       ^`. <br>
I'm not too familiar with how to perform builds, so to elaborate on your method, how did you perform the build after checking out master? Also, what would be the fastest way to get the other tools I need from the ZIP file into my project? Thanks in advance.

**Comment by Unlocker** [comment]
@neilpat1995 There is an issue with OS Windows for the existing stable versions. Andy mentioned that issue was fixed in the current snapshot and gave advice to build 0.8.0-SNAPSHOT from sources.
You can read the [article](https://github.com/andypetrella/spark-notebook/blob/master/docs/build_from_source.md) with detailed instructions. If you will have any questions then give me to know and I will try to help.

**Comment by neilpat1995** [comment]
@Unlocker Thanks for the resource; I attempted to create the build and got to the end of the "Launch the server" section, where I ran the server using `run`. This gave the output: <br>
```
[info] Compiling 1 Scala source to C:\Users\Neil\Documents\GitHub\spark-notebook
\modules\common\target\scala-2.10\classes...

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Neil/.ivy2/cache/org.slf4j/slf4j-log
4j12/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Neil/.ivy2/cache/ch.qos.logback/logb
ack-classic/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.cl
ass]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
--- (Running the application, auto-reloading is enabled) ---

log4j:WARN No appenders could be found for logger (org.jboss.netty.channel.socke
t.nio.SelectorUtil).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in
fo.

(Server started, use Ctrl+D to stop and go back to the console...) 
```
<br>

After a while, the terminal also shows that Scala and CoffeeScript sources are also compiling.
I then tried to navigate to localhost:9000 and localhost:9001, but neither of these worked. Where exactly should the server be listening? My understanding was that I should be able to connect through localhost:9000 on my browser, as it did when I originally downloaded the ZIP file from the link in my previous post.

**Comment by Unlocker** [comment]
@neilpat1995 This way is not optimal I think. You can run `sbt dist` and grab you personal zip inside the `/target/universal` directory.

**Comment by elbamos** [comment]
I'm seeing this also, running a fresh build from the website with the latest master, and running it from docker. 

```
2 + 2
```
```
<console>:12: error: not found: value globalScope
       globalScope.sparkContext.setJobGroup("cell-563D92872092468F86451106E4DE9F9A", "run-1513304439478: 2  2")
```

I'm also seeing, in error logs, 
```
[notebook.client.ReplCalculator] Error in init script: java.lang.IllegalArgumentException: System memory 415760384 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration
```
Even though `spark.driver.memory` is set to 4GB.

**Comment by dfesenko** [comment]
@elbamos I have the same issue with `1+1`. Were you be able to find a workaround for this problem?

**Comment by HelmutZechmann** [comment]
I also had memory issues when running the container on docker for mac. The error message was
```
...
Error in init script: java.lang.IllegalArgumentException: System memory 415760384 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark 
...
```
Assigning more memory to docker for mac in `Preferences`->`Advanced` solved the problem for me.

**Comment by frbayart** [comment]
With Docker there are 2 points to check with memory:

- check the Docker memory: On Mac Docker, click on Docker icon > Preferences > set CPU 4 and RAM 8GB
- create an application.ini file on your computer et share it on docker run

`application.ini`
-J-Xmx4G

docker run:
`docker run -it --rm -p 9001:9001 -v /Users/frbayart/application.ini:/opt/docker/conf/application.ini --name=test andypetrella/spark-notebook:0.9.0-SNAPSHOT-scala-2.11.8-spark-2.2.1-hadoop-2.7.2-with-hive`
